### ISSUE TITLE
Schema and data source props missing

### ISSUE THREAD

**Issue by nsridatta** [hendisantika/jwt-spring-boot-security-angular#1]
Hi,
I have gone thru your code and it is greatly written but we shall get error while starting the app, as the AutoConfig would look for Data source props(here H2) and also the schema for the data base should also be given.
Please kindly update those which will be really helpful to us. Below are the sample props you can play with

#H2 Datasource properties
spring.datasource.url=jdbc:h2:mem:liquibaseDisabledDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#Hibernate properties
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=auto
spring.jpa.properties.hibernate.format_sql=true

Thanks

**Comment by hendisantika** [comment]
Hi @nsridatta ,

Thank You for your suggestion.

You can pull the latest code. I already bug fixed it.

**Comment by nsridatta** [comment]
Thanks
